project:
  type: website
  
website:
  title: "ISSS608 Group Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Prototype"
        menu:
          - href: Proposal/proposal.qmd
            text: Proposal
          - href: Proposal/clustering.qmd
            text: Clustering Analysis
          - href: Proposal/time_analysis.qmd
          - href: Proposal/Storyboard.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
