project:
  type: website
  
website:
  title: "ISSS608 Group Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Proposal.qmd
        text: Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
